### ISSUE TITLE
ask for help：How do I import bpy on a Windows system？

### ISSUE THREAD

**Issue by nostayup** [hassony2/obman_render#1]
How do I import bpy on a Windows system？thanks ~

**Comment by hassony2** [comment]
Hi @nostayup ,

bpy is only available if you run the script from blender (not from your system's python).
If you run `path/to/your/blender -noaudio -t 1 -P blender_grasps_sacred.py -- '{"frame_nb": 10, "frame_start": 0, "results_root": "datageneration/tmp", "background_datasets": ["white"]}'` it will run using blender's python and bpy should be available :)

Best,

Yana

**Comment by liwenssss** [comment]
> How do I import bpy on a Windows system？thanks ~

did you solve how to run in windows?
