### ISSUE TITLE
I received different models from 'SMPL for Python Users'

### ISSUE THREAD

**Issue by Saafke** [hassony2/obman_render#7]
When I go to the SMPL website, I have the option to download either:

Download version 1.0.0 for Python 2.7 (10 shape PCs)
or
Download version 1.1.0 for Python 2.7 (all 300 shape PCs)

In both cases, I receive .pkl files (not .fbx like it says in the instructions):

models/basicModel_f_lbs_10_207_0_v1.1.0.pkl
models/basicModel_m_lbs_10_207_0_v1.1.0.pkl

I also don't receive 'SMPLH_female.pkl'.

**Comment by dimtziwnas** [comment]
Hi Saafke, I think you try to download the model files from the wrong website. 

Wrong website:    https://smpl.is.tue.mpg.de   (Here you will find the SMPL model - this has no hand modeling)
Correct website:  https://mano.is.tue.mpg.de  (Here you will find the MANO hand model, and SMPL+H model of body+hand)

If you follow carefully Yana's [read_me](https://github.com/hassony2/obman_render), by clicking only the provided instructions and URLs, you will only end up at the correct website ;)

**Comment by Saafke** [comment]
I used this to solve the problem:

Copy into the assets/models folder:
- models from MANO
- I found the correct SMPL FBX models in the "SMPL for MAYA" package (https://smpl.is.tue.mpg.de/downloads)
